name: Solar System Workflow
on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'features/*'
    
jobs:
    unit-testing:
        name: NPM Testing
        runs-on: ubuntu-latest
        services:
          mongo-db:
            image: devopsprozy/mongo-db:latest
            ports:
              - 27017:27017
        env:
          MONGO_URI: 'mongodb://localhost:27017/superData'
          MONGO_USERNAME: ${{ vars.USERNAME }}
          MONGO_PASSWORD: ${{ secrets.PASSWORD }}
        steps:
          - name: Download Repo
            uses: actions/checkout@v4
          - name: Setup NPM
            uses: actions/setup-node@v4
            with:
              node-version: 20
          - name: Install Dependencies
            run: npm install
          - name: Test Application
            run: npm test
          - name: Upload Test Results
            uses: actions/upload-artifact@v3
            with:
              name: Workflow-Result
              path: test-results.xml

    code-coverage:
      name: Checking Code Coverage
      runs-on: ubuntu-latest
      steps:
        - name: Download Repo
          uses: actions/checkout@v4
        - name: Setup NPM
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Install Dependencies
          run: npm install
        - name: Code Coverage
          run: npm run coverage
        - name: Upload Test Results
          uses: actions/upload-artifact@v3
          with:
            name: Workflow-Result
            path: results.xml
            retention-days: 5